name: Analyze and Generate Lang


on: [push]

permissions:
  contents: write

jobs:
  analyze_and_generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Run Analyzer and Generator
        run: |
          echo repository: $GITHUB_WORKSPACE 
          cd $GITHUB_WORKSPACE/TranslationRunner
          dotnet TranslationRunner.dll
          cd ..
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: analyzed & generated & updated versions
          
